name: documatio CI

on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive-full curl
      - name: Set up documatio
        run: make depend
      - name: Build with documatio
        run: make build
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            out/release/all.zip
      - name: Publish to GitHub pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out/docs
          git-config-name: GitHub Pages Bot
          git-config-email: bot@example.com
